print("Please fill in the blanks below:")
print("_____(name)_____'s favorite subject in school is _____(subject)_____.")
name = input("What is name? ")
subject = input("What is subject? ")
print(f"{name}'s favorite subject in school is {subject}.")